#!/usr/bin/env bash
time ./h_algorithm graph1 
time ./h_algorithm graph2 
time ./h_algorithm graph3 
time ./h_algorithm graph4 
time ./h_algorithm graph5 
time ./h_algorithm graph6 
time ./h_algorithm graph7 
time ./h_algorithm graph8 
time ./h_algorithm graph9 
time ./h_algorithm graph10 
time ./h_algorithm graph11 
time ./h_algorithm graph12 
time ./h_algorithm graph13 
time ./h_algorithm graph14 
time ./h_algorithm graph15 
time ./h_algorithm graph16 
time ./h_algorithm graph17 
time ./h_algorithm graph18 
time ./h_algorithm graph19 
time ./h_algorithm graph20 
time ./h_algorithm graph21 
time ./h_algorithm graph22 
time ./h_algorithm graph23 
time ./h_algorithm graph24 
time ./h_algorithm graph25 
time ./h_algorithm graph26 
time ./h_algorithm graph27 
time ./h_algorithm graph28 
time ./h_algorithm graph29 
time ./h_algorithm graph30 
time ./h_algorithm graph31 
time ./h_algorithm graph32 
time ./h_algorithm graph33 
time ./h_algorithm graph34 
time ./h_algorithm graph35 
time ./h_algorithm graph36 
time ./h_algorithm graph37 
time ./h_algorithm graph38 
time ./h_algorithm graph39 
time ./h_algorithm graph40 
time ./h_algorithm graph41 
time ./h_algorithm graph42 
time ./h_algorithm graph43 
time ./h_algorithm graph44 
time ./h_algorithm graph45 
time ./h_algorithm graph46 
time ./h_algorithm graph47 
time ./h_algorithm graph48 
time ./h_algorithm graph49 
time ./h_algorithm graph50 